plugins {
    id 'java'
}

configurations {
    bundleLib
}

group = 'berlin.giz.keycloak.mappers'
version = '1.0.0'

ext {
    keycloakVersion = '26.5.5'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.keycloak:keycloak-services:$keycloakVersion"
    implementation "org.keycloak:keycloak-server-spi:$keycloakVersion"
    implementation "org.keycloak:keycloak-server-spi-private:$keycloakVersion"
}

test {
    useJUnitPlatform()
}

jar {
    from {
        configurations.bundleLib.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
